version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    
  server:
    build: ./server
    # links:
    #   - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - $PWD/server/build:/server/build
    command: npm run dev
    env_file:
      - .env

  pdf_handler:
    build: ./pdf_handler
    # links:
    #   - redis
    #   - server
    environment:
      - REDIS_URL=redis://redis:6379
      - DOCS_FOLDER=./app/data/docs/
      - TEMP_FOLDER=./app/data/temp/
      - OUTPUT_FOLDER=./app/data/output/
      - STAMP_FOLDER=./app/data/stamps/
    command: python3 /worker/app/app.py
    volumes:
      - $PWD/pdf_handler/app:/worker/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server